Algoritmo "petPlace"
//COMPRA POR QUILO  - Ração
// DESCONTO
//QUANTIDADE DE UNIDADE
Var
opcao : caractere
Inicio
escreval("*********catalágo************")
escreval("1 - Ração 15 KG- R$ 50,00 ")
escreval("2 - Coleira 15 KG- R$ 20,00 ")
escreval("3- Petisco 15 KG- A partir de R$ 20,00 ")
escreval("4- Casinha de cachorro 15 KG- R$ 100,00 ")
escreval("5- Potes 15 KG- A partir de R$ 15,00 ")
escreval("6 - Cancelar")
escreval("7 - Carrinho")

leia(opcao)


Fimalgoritmo